### ISSUE TITLE
1.0.0-beta3 remote video track not work

### ISSUE THREAD

**Issue by ron194** [twilio/video-quickstart-objc#33] opened 2016-12-03 17:37 UTC
1.0.0-beta3 remote video track not works
FYI, beta2 works fine. 
Thanks Twilio team.

**Comment by ceaglest** [comment] 2016-12-05 22:48
@ron194 Can you be more specific? Are you not getting any video frames from the track? Is the track not added, where it was before? What kind of renderer do you use, and how do you add it to the `TVIVideoTrack`?

Info or Debug level logs, and a description of your usage would be helpful in diagnosing the problem.

**Comment by ceaglest** [comment] 2016-12-13 21:54
Hi @ron194,

I never heard back from you on this one. We've just released `1.0.0-beta4` for iOS, though I'm not aware of any changes related to remote video tracks in this release. Feel free to try out this new release to see if it resolves your problem. If it still persists please send Info or Debug level logs and a description of your use case.

Cheers,
Chris

**Comment by ceaglest** [comment] 2017-01-20 04:15
@ron194 I'm going to close this issue since we never heard back from you. We just released `1.0.0-beta5` of our iOS SDK today - if you are still experiencing problems with remote video tracks then feel free to reopen this issue.

Thanks,
Chris

**Comment by marioacarvalho** [comment] 2017-02-16 15:28
Hi @ceaglest I'm experiencing this issue. I'm able to connect to the room, I see that Room has 1 participant, set the delegate but afterwards nothing happens. Only when other participant leaves the room, `room:(TVIRoom *)room participantDidDisconnect:(TVIParticipant *)participant` is called..

Any idea? 

Happens with `beta6` and `beta7`.

**Comment by ceaglest** [comment] 2017-02-16 18:50
Hi @marioacarvalho,

Are you experiencing this issue with the QuickStart or your own app? The example only supports a single participant but ideally you should handle all connected participants in `didConnectToRoom`.

```
- (void)didConnectToRoom:(nonnull TVIRoom *)room {
    NSLog(@"didConnectToRoom: %@", room);

    for (TVIParticipant *participant in room.participants) {
        participant.delegate = self;
    }
}

- (void)participant:(TVIParticipant *)participant addedVideoTrack:(nonnull TVIVideoTrack *)videoTrack {
    NSLog(@"Participant %@ added video track %@", [participant identity], videoTrack);
    // Do something with the track, like add a renderer..
}
```

Could you share debug or info level logs reproducing the issue?

- Chris

**Comment by ceaglest** [comment] 2017-02-16 19:53
@marioacarvalho I updated the code snippet above to be a little clearer. The important thing to note is that you won't get `room:ParticipantDidConnect:` callbacks for Participants which have already connected to the Room.

**Comment by ceaglest** [comment] 2017-02-22 21:23
@marioacarvalho are you still having issues with track events not being raised?

**Comment by ceaglest** [comment] 2017-03-09 00:29
Closing this ticket due to inactivity. I think this was just confusion about the API contract, and I did my best to explain it above.

**Closed by ceaglest** 2017-03-09 00:29 UTC
Labels: question
