### ISSUE TITLE
Twilio Video ver 2.5 can't run in iOS 9 simulator

### ISSUE THREAD

**Issue by nguyentuananh56hust** [twilio/video-quickstart-objc#130] opened 2018-10-01 10:15 UTC
Hi guys, in webpage I see twilio support for iOS 9.0+ but when I run in iOS 9.0 simulator, application has been crashed. Application still run fine in iOS 10.0+ simulator.

Can fix it to run in iOS 9.0? Many thank!
Sorry for my bad English!

Debug log:

`dyld: Library not loaded: /System/Library/Frameworks/MetalKit.framework/MetalKit
  Referenced from: /Users/tuananh/Library/Developer/CoreSimulator/Devices/1B30B596-508F-4445-B5EE-BBA68AD4D85D/data/Containers/Bundle/Application/4221F023-AE46-4FB4-83B3-4DE7031CD13A/ObjCVideoQuickstart.app/Frameworks/TwilioVideo.framework/TwilioVideo
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/MetalKit.framework/MetalKit: mach-o, but not built for iOS simulator`

**Comment by piyushtank** [comment] 2018-10-02 05:03
@nguyentuananh56hust Thanks for reaching out. I am able to reproduce the problem you have reported. I will get back to you tomorrow with more details.

**Comment by piyushtank** [comment] 2018-10-04 04:35
The problem was originally introduced in iOS Video SDK version `2.3.0-preview2`. We have created a bug ISDK-2207 internally to track the bug. We are planning to fix and release the SDK in a few days(most likely early next week).

**Comment by nguyentuananh56hust** [comment] 2018-10-04 05:13
Oh thank you very much!

**Comment by paynerc** [comment] 2018-10-11 16:32
@nguyentuananh56hust,

I have fixed this issue and it will be going to QA shortly. I will comment on this issue once it has been validated and the release has been cut. I would expect this in the next few days.

**Comment by paynerc** [comment] 2018-10-18 16:39
@nguyentuananh56hust 

Yes, the issue only affects the simulator. On another note, we have just release Twilio Video iOS `2.5.3`, which fixes this issue. Please grab the latest version and try running your application in the iOS 9 simulator.

Let me know if you have any further issues.

Ryan

**Comment by ceaglest** [comment] 2018-10-26 16:44
Hi @nguyentuananh56hust,

Now that [2.5.3](
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#253-october-18-2018) has been available for some time with the fix, I'm closing out this issue. Please re-open if you are still able to reproduce the crash.

Thanks again for reporting this regression. We've taken steps to test on a wider range of simulators to hopefully prevent these types of bugs from occurring again.

Cheers,
Chris

**Closed by ceaglest** 2018-10-26 16:44 UTC
Labels: bug
